"""Does anything outside the boards still name a part the boards no longer carry?

    py -3.12 elec/bom_audit.py            # the report; exit 1 on a hard finding
    py -3.12 elec/bom_audit.py --docs     # also list every stale mention in the prose

WHY THIS EXISTS (2026-10-06). An order-day stock list named a photodiode with 95 pieces
in stock as a risk to the build. It was on no board: the optical pickup had moved to a
different photodiode weeks earlier and the old name lived on in BOM.md. Every other check
here starts from a BOARD and asks whether the paperwork agrees with it (bom_check,
mpn_check, lcsc_check). None starts from the PAPERWORK and asks whether a board still
wants what it names, so a retired part is invisible until somebody reads it as current.

THE TRUTH IS THE NETLISTS OF fab.BOARDS, regenerated by each generator. Not `elec/out/*`:
that directory is untracked and keeps the files of boards that are no longer in the
design, and a tool that globs it counts their parts (tools/lcsc_prices.py did).

What is checked, and how hard:
  HARD  a part on a board with no LCSC code: a maker's part missing from fab.LCSC, or a
        passive whose (value, footprint) is missing from fab.PASSIVES. A blank row is
        filled in by the fab's own matcher, which has picked the wrong package
  HARD  a part whose description cites one LCSC code while fab.LCSC orders another (the
        fab reads fab.LCSC; the description is what a person reads, and on 2026-10-06
        the output panel's digital pot cited the code of a 4.7 uF capacitor)
  HARD  elec/prices.json prices a designator under a part number its board does not carry
  HARD  elec/prices.json prices a designator its board does not have
  HARD  a BOM.md parts-table row names a part number that is on no board
  soft  fab.LCSC carries a code no board uses (dead entry: delete it)
  soft  a tracked geometry file for a board that is not in fab.BOARDS
  HARD  docs/order-parts.md (the generated list of what is on the boards) is stale
  HARD  a BOM.md designator row names a different part than its board (bom_check.py,
        which reads the fab packages: skipped, and said so, when they are not built)
  soft  prose that names a retired part (--docs): history is allowed to, a current
        instruction is not, and only a reader can tell which. A section whose heading
        says HISTORY is not searched
"""
from __future__ import annotations

import glob
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))
import lcsc_prices as L  # noqa: E402


def boards():
    return [os.path.basename(p)[:-4] for p in L.design_netlists()]


# A value that is a rating, not a maker's part: generic passives, pads, jumpers, labels.
GENERIC = re.compile(
    r"^(\d+(\.\d+)?\s*(p|n|u|µ)F\b.*|\d+(\.\d+)?[RkM]\d*\b.*|\d+R\b.*|0R|DNP|TERM|THROW|SWD|"
    r"BRINGUP|TP|PAD|NC|MountingHole.*|Fiducial.*|.*SolderJumper.*)$", re.I)


# Designators that are copper, not parts: test pads, jumpers, holes, fiducials.
NOT_A_PART = re.compile(r"^(TP|JP|H|FID|MH)\d")


FOOTPRINT = {}                                      # (board, ref) -> footprint name
COPPER = re.compile(r"^(TestPoint|NetTie|Fiducial|SolderJumper|MountingHole)")


def truth():
    """({board: {ref: (value, code)}}, conflicts) for every board in the design."""
    codes, pairs = L.lcsc_map(), L.passive_map()
    out, conflicts = {}, []
    for path in L.design_netlists():
        b = os.path.basename(path)[:-4]
        out[b] = {}
        for ref, val, _fp, inline in L.netlist_parts(path):
            table = codes.get(val)
            if inline and table and inline != table:
                conflicts.append("%s %s '%s': its description cites %s, fab.LCSC orders %s"
                                 % (b, ref, val, inline, table))
            out[b][ref] = (val, pairs.get((val, _fp.split(":")[-1])) or table or inline)
            FOOTPRINT[(b, ref)] = _fp.split(":")[-1]
    return out, conflicts


def main(argv):
    show_docs = "--docs" in argv
    hard, soft = [], []
    T, conflicts = truth()
    missing = []
    hard += conflicts
    uncoded = {}
    on_board = {}                                   # value -> boards
    used_codes = {}
    for b, parts in T.items():
        for ref, (val, code) in parts.items():
            on_board.setdefault(val, set()).add(b)
            if code:
                used_codes.setdefault(code, set()).add(b)
            elif not NOT_A_PART.match(ref) and not COPPER.match(FOOTPRINT[(b, ref)]):
                uncoded.setdefault((val, FOOTPRINT[(b, ref)]), []).append("%s %s" % (b, ref))
    for (val, fp), where in sorted(uncoded.items()):
        hard.append("no LCSC code for '%s' in %s (%d part(s): %s%s) -- add it to fab.%s"
                    % (val, fp, len(where), ", ".join(where[:3]),
                       " ..." if len(where) > 3 else "",
                       "PASSIVES" if GENERIC.match(val) else "LCSC"))
    hard = sorted(set(hard))

    # fab.LCSC entries nothing uses
    codes = L.lcsc_map()
    dead = {v: c for v, c in codes.items() if v not in on_board}
    for v, c in sorted(dead.items()):
        soft.append("fab.LCSC: '%s' (%s) is on no board" % (v, c))

    # prices.json, designator by designator
    pj = json.load(io.open(os.path.join(HERE, "prices.json"), encoding="utf-8"))
    gone = {}
    for key, rec in sorted((pj.get("parts_by_ref") or {}).items()):
        if key.startswith("_"):
            continue
        b, _, ref = key.partition(":")
        if b not in T:
            gone.setdefault("'%s' is not a board in the design" % b, []).append(ref)
            continue
        if ref not in T[b]:
            gone.setdefault("%s no longer has them" % b, []).append(ref)
            continue
        val, code = T[b][ref]
        what = rec.get("what", "")
        m = re.match(r"(\S+)\s+(C\d+)\b", what)
        if m and code and m.group(2) != code:
            hard.append("prices.json %s: priced as %s %s, the board carries %s %s"
                        % (key, m.group(1), m.group(2), val, code))

    for why, refs in sorted(gone.items()):
        hard.append("prices.json prices %d designator(s) (%s ...): %s -- "
                    "tools/lcsc_prices.py removes them" % (len(refs), ", ".join(refs[:4]), why))

    # tracked geometry for boards that are gone
    for p in sorted(glob.glob(os.path.join(HERE, "geom", "*.geom.json"))):
        name = os.path.basename(p)[:-len(".geom.json")]
        if name not in T and name not in missing:
            soft.append("elec/geom/%s.geom.json: not a board in fab.BOARDS" % name)

    # the prose: any LCSC code or dead part number
    mating = set(L.HOUSING.values()) | set(L.CRIMP.values())
    for (v, f), c in sorted(L.passive_map().items()):
        if not any(val == v and FOOTPRINT[(b, ref)] == f
                   for b, parts in T.items() for ref, (val, _c) in parts.items()):
            soft.append("fab.PASSIVES: ('%s', '%s') (%s) is on no board" % (v, f, c))
    known = set(used_codes) | mating
    dead_names = set(dead)
    docs = [os.path.join(ROOT, "BOM.md"), os.path.join(ROOT, "INSTALL_NOTES.md")]
    docs += sorted(glob.glob(os.path.join(ROOT, "docs", "*.md")))
    mentions = []
    for p in docs:
        rel = os.path.relpath(p, ROOT).replace("\\", "/")
        history = False
        for n, line in enumerate(io.open(p, encoding="utf-8", errors="replace"), 1):
            if line.startswith("#"):
                history = "HISTORY" in line
            if history or rel == "docs/order-parts.md":
                continue
            stale = sorted(set(c for c in re.findall(r"(?<![\w-])C\d{4,9}\b", line)
                               if c not in known))
            names = sorted(nm for nm in dead_names if nm in line)
            if not stale and not names:
                continue
            row = line.lstrip().startswith("|")
            struck = "~~" in line
            mentions.append((rel, n, row, struck, stale, names, line.strip()))
    # a parts-table row (qty | designator | part ...) naming something no board has
    for rel, n, row, struck, stale, names, text in mentions:
        cells = [c.strip() for c in text.strip("|").split("|")]
        is_parts_row = (row and len(cells) >= 3 and re.match(r"^\d+$", cells[0] or "")
                        and re.match(r"^[A-Z]{1,3}\d", cells[1] or ""))
        if is_parts_row and not struck and rel == "BOM.md":
            hard.append("%s:%d parts row names %s, on no board: %s"
                        % (rel, n, ", ".join(stale + names), text[:110]))

    import order_list
    if order_list.render() != io.open(order_list.OUT, encoding="utf-8").read().replace(
            "\r\n", "\n"):
        hard.append("docs/order-parts.md is stale: run tools/order_list.py")
    try:
        import bom_check
        for board, des, part, code, val, line in bom_check.check()[0]:
            hard.append("BOM.md:%d %s says %s %s, %s places %s"
                        % (line, des, part, code, board, val))
    except Exception as exc:
        soft.append("bom_check did not run (fab packages not built here?): %r" % (exc,))

    print("boards: %d in the design, %d netlists read" % (len(boards()), len(T)))
    print("parts: %d maker part numbers, %d LCSC codes in use" % (
        sum(1 for v in on_board if not GENERIC.match(v)), len(used_codes)))
    print("\nHARD (%d)" % len(hard))
    for h in hard:
        print("  " + h)
    print("\nsoft (%d)" % len(soft))
    for s in soft:
        print("  " + s)
    by_file = {}
    for m in mentions:
        by_file.setdefault(m[0], []).append(m)
    print("\nprose naming a part or code that is on no board: %d line(s) in %d file(s)"
          % (len(mentions), len(by_file)))
    for rel, ms in sorted(by_file.items(), key=lambda kv: -len(kv[1])):
        print("  %4d  %s" % (len(ms), rel))
        if show_docs:
            for _rel, n, row, struck, stale, names, text in ms:
                print("        %d: [%s] %s" % (n, ", ".join(stale + names), text[:120]))
    return 1 if hard else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
