"""What is on the boards, written out: docs/order-parts.md, generated.

    py -3.12 tools/order_list.py            # rewrite docs/order-parts.md
    py -3.12 tools/order_list.py --check    # exit 1 if the file on disk is stale

WHY A GENERATED FILE (2026-10-06). BOM.md's board sections are a design record: they say
what was chosen and why, in the order it was decided, and a part that was replaced is
still named in the paragraph that chose it. Read for "what do we order", that record
answered with a photodiode that had left the board weeks before. This file is the answer
to that one question and nothing else, and no hand writes it: every row is a part in a
netlist of a board in fab.BOARDS, with the LCSC code fab.py orders it under.

No prices and no stock here, on purpose: both move daily, and a file that has to match
its generator byte for byte cannot hold a number that changes by itself. Prices are
elec/prices.json (tools/lcsc_prices.py), stock is read on the day.
"""
from __future__ import annotations

import collections
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import lcsc_prices as L  # noqa: E402

OUT = os.path.join(ROOT, "docs", "order-parts.md")
NOT_A_PART = re.compile(r"^(TP|JP|H|FID|MH)\d")


def _key(ref):
    m = re.match(r"([A-Za-z]+)(\d+)(.*)", ref)
    return (m.group(1), int(m.group(2)), m.group(3)) if m else (ref, 0, "")


def _refs(refs):
    """R1, R2, R3, R7 -> 'R1-R3, R7' (suffixed designators are listed as they are)."""
    refs = sorted(refs, key=_key)
    out, run = [], []

    def flush():
        if len(run) > 2:
            out.append("%s-%s" % (run[0], run[-1]))
        else:
            out.extend(run)

    for r in refs:
        k = _key(r)
        if run and not k[2] and not _key(run[-1])[2] \
                and k[0] == _key(run[-1])[0] and k[1] == _key(run[-1])[1] + 1:
            run.append(r)
        else:
            flush()
            run = [r]
    flush()
    return ", ".join(out)


def render():
    codes = L.Codes()
    lines = ["# What is on the boards", "",
             "Generated by `tools/order_list.py` from the netlists of the boards in "
             "`elec/fab.py`. Do not edit: change the board's generator and re-run. "
             "`elec/bom_audit.py` fails when this file is stale.", "",
             "A part that is not in this file is not on a board, whatever another "
             "document says about it.", ""]
    total = collections.OrderedDict()
    boards = []
    for path in L.design_netlists():
        b = os.path.basename(path)[:-4]
        per10 = L.board_qty(b)
        n = None if per10 is None else per10 // L.ORDER_INSTRUMENTS
        groups = collections.OrderedDict()
        pads = []
        for ref, val, fp, inline in L.netlist_parts(path):
            if NOT_A_PART.match(ref):
                pads.append(ref)
                continue
            code = codes.get(val, fp, inline)
            groups.setdefault((val, code, fp.split(":")[-1]), []).append(ref)
        boards.append((b, n, groups, pads))
        for (val, code, fp), refs in groups.items():
            if code and n:
                t = total.setdefault(code, [val, 0, []])
                t[1] += len(refs) * n
                if b not in t[2]:
                    t[2].append(b)

    lines += ["## Every coded part, per instrument", "",
              "| Part | LCSC | Per instrument | Boards |", "|---|---|--:|---|"]
    for code, (val, n, where) in sorted(total.items(), key=lambda kv: (kv[1][0].lower(), kv[0])):
        lines.append("| `%s` | %s | %d | %s |" % (val, code, n, ", ".join(where)))
    lines.append("")

    for b, n, groups, pads in boards:
        lines += ["## `%s`" % b, "",
                  "%s per instrument. %d placed part(s) in %d line(s)%s." % (
                      "?" if n is None else n, sum(len(r) for r in groups.values()),
                      len(groups),
                      "; %d pad(s) and jumper(s) that are copper, not parts" % len(pads)
                      if pads else ""), "",
                  "| Qty | Designators | Part or value | Package | LCSC |",
                  "|--:|---|---|---|---|"]
        rows = sorted(groups.items(), key=lambda kv: (kv[0][1] is None, _key(sorted(kv[1], key=_key)[0])))
        for (val, code, fp), refs in rows:
            lines.append("| %d | %s | `%s` | %s | %s |" % (
                len(refs), _refs(refs), val, fp, code or "NO CODE"))
        lines.append("")
    return "\n".join(lines)


def main(argv):
    text = render()
    if "--check" in argv:
        old = io.open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else ""
        if old.replace("\r\n", "\n") != text:
            print("docs/order-parts.md is stale: run tools/order_list.py")
            return 1
        print("docs/order-parts.md is current")
        return 0
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote docs/order-parts.md (%d lines)" % text.count("\n"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
